# Generated by Django 3.0.2 on 2020-01-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
