# Generated by Django 3.0.2 on 2020-01-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200130_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
