# Generated by Django 3.0.2 on 2020-01-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='user1',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
