# Generated by Django 3.0.2 on 2020-01-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_choice_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user1',
            new_name='voter',
        ),
    ]
