# Generated by Django 3.0.2 on 2020-01-31 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200131_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='voter',
            new_name='voter1',
        ),
    ]
